### ISSUE TITLE
Unable to make ssh connection to EKS worker nodes

### ISSUE THREAD

**Issue by HughWilliams** [nithu0115/kubectl-ssh-plugin-eks#1]
Attempting to make a ssh connection to my EKS worker nodes is failing with the error:
```
$ kubectl plugin ssh ip-192-168-107-182.ec2.internal -i ~/certificates/MY-KEYPAIR.pem 
MissingParameter: status
SSHing into Worker Node with IP: The
code:
ssh: Could not resolve hostname the: nodename nor servname provided, or not known
Can't SSH
error: exit status 1
$
```
Why does  the kubectl ssh plugin think the Worker Node name or IP is "The" ???

**Comment by nithu0115** [comment]
@HughWilliams - I apologize for the delay in responding back on the issue. 

Could you please run ```kubectl  describe node <node name>``` and post me the output. It looks like IP which is fetched is returning "The"

**Comment by ankon** [comment]
The problem here is that the kubernetes version is "too new" (1.11+): The `script_ssh.sh` script depends on `.spec.externalID`, which was deprecated and now got removed.

> Kubelets will no longer set externalID in their node spec. This feature has been deprecated since v1.1. (#61877, @mikedanese)

(https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#kubernetes-111-release-notes, https://github.com/kubernetes/kubernetes/pull/61877)
